# Generated by Django 4.2.23 on 2025-08-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الشكوى')),
                ('desc', models.CharField(max_length=50, verbose_name='وصف')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='السعر')),
                ('days', models.IntegerField(verbose_name='ايام انهاء الطلب')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
