# Generated by Django 4.2.23 on 2025-08-06 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedComplaintModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='اسم المستخدم')),
                ('email', models.CharField(max_length=50, verbose_name='بريد الالكتروني')),
                ('imgae', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('progress', models.CharField(choices=[('1', 'ادخال المعلومات'), ('2', 'يتم مراجعة الطلب'), ('3', 'الدفع'), ('4', 'مكتمل')], default='1', max_length=50, verbose_name='التقدم')),
                ('created_date', models.DateTimeField()),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.complaintsmodel', verbose_name='الشكوى')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
        ),
    ]
