# Generated by Django 4.2.23 on 2025-08-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_submittedcomplaintmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedcomplaintmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
