# Generated by Django 4.2.23 on 2025-08-06 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_submittedcomplaintmodel_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submittedcomplaintmodel',
            old_name='imgae',
            new_name='image',
        ),
    ]
